# Generated by Django 5.0.6 on 2024-05-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=200)),
                ('house_number', models.CharField(max_length=20)),
                ('entrances', models.PositiveIntegerField(default=1)),
                ('apartments_per_entrance', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
